require("dotenv").config(); // to be removed when we switch over to git based keys

const Discord = require("discord.js");
const bot = new Discord.Client();

const TOKEN = process.env.TOKEN;

bot.on("ready", () => {
  console.info("Logged in as {bot.user.tag}!");
});

bot.login(TOKEN);

//Command prefix
const prefix = "!"
const team_number = 69;
const Name = "Samson";
const discordName = "Samson#9999";
const email = "samson@spaghetti.com";

bot.on('message', message => {
	if (message.content === '!teams') {

    if(teams.teams.length === 0){
      //Checks to see if there are any teams
      message.channel.send("There are currently no teams registered in the system :avocado:")
    }else{
      //Sends out an embed for each team
      for(let i = 0; i < teams.teams.length; i++){
        //iterate through each team and make an embed
        
        const teamMemberEmbed = createEmbed(69, "Samson Hua", "Samson#9999", "samson@spaghetti.com")
        //Publish team stats
        message.channel.send(teamMemberEmbed);
      }
      
      
    }
  }
  //Dab Function: Dabs on the server when someone requests it
  else if(message.content === "!dab"){

    message.channel.send("Get Dabbed On :smile:");
  
  //Help Function: Returns commands to user
  }else if (message.content === "!help"){

    message.channel.send("Get your own help bro :angry:");
  }

});

//Team Embed Generator
function createEmbed(team_number, Name, discordName, email){

  const teamMemberEmbed = new Discord.MessageEmbed()
      .setColor('#FF08F0')
      .setTitle(`Team #${team_number}`)
      .setAuthor('HYL Team Management Bot', 'https://i.pinimg.com/originals/7b/cf/da/7bcfda3e4a0943c35a89f12fae1cefb5.jpg', 'https://hackyourlearning.ca/')
      .setDescription('=============================')
      .addFields(
        { name: `${Name} (${discordName})`, value: `${email}`},
        { name: `${Name} (${discordName})`, value: `${email}`},
        { name: `${Name} (${discordName})`, value: `${email}`},
        { name: `${Name} (${discordName})`, value: `${email}`},
      )
      .setTimestamp()
      .setFooter('Generated by HackYourLearning Bot', 'https://fcbk.su/_data/stickers/bugcat_capoo/bugcat_capoo_12.png');

  return teamMemberEmbed;

}


//Team Class Code
class User {
  constructor() {
    this.DiscordNames = "";
    this.DiscordTags = "";
    this.DiscordIds = "";
    this.Names = "";
    this.Emails = "";
  } 
}

class Team extends User{
  constructor(id){
    super();
    this.teamId = id;
    this.teamMembers = [];
  }
}

class TeamList extends Team{

  constructor(ListName){
    super();
    this.listName = ListName;
    //Object to store all the teams in
    this.teams = [];
  }

  //Creates amount of teams based on number of teams
  createTeams(numberOfTeams){
    for(let i = 0; i < numberOfTeams; i++){
      //Creates a team
      let team = new Team()
      this.teams.push(team);
    }
  }

  //Returns all teams
  listAllTeams(){
    if (this.teams.length == 0){
        console.log("There are no teams in this list");
    }else{
        return this.teams;
    }
    
  }

}

//Functions at the bottom
let teams = new TeamList("Hackathon Participants");