const Discord = require("discord.js");

module.exports = {
	name: 'messagescheduler',
	description: 'Schedule a message to everyone',
	execute(message, args) {
        let date = new Date(args[0], args[1], args[2], args[3], args[4], 0, 0);
        var processedMessage = "";
        for(i = 5; i < args.length; i++){
            processedMessage += args[i]
            processedMessage += " "
        }
        var interval = setInterval( function(){
            let refDate = new Date()
            var theMessage = new Discord.MessageEmbed()
                        .setColor('#6a0dad')
                        .setTitle("Important")
                        .setAuthor('HYL Management Bot')
                        .setDescription(processedMessage)
                        .setFooter("Generated by Hack Your Learning Bot");
            if((date.getTime() - refDate.getTime()) > 0){
                message.guild.members.cache.forEach(user => {
                        user.send(theMessage); 
                }) 
                clearInterval(interval);
            }
        }, 10000)
    },
};